[Feature] add setting site logo support for group with applications perms
pnp/pnpcore pull request #1519
Opened 2024-09-01 15:40 UTC by danielpastoor

I changed the api call from SharePoint to the Graph api call so it is now possible to set the site logo of a group with application permission and still support it for delegated permissions.

Also I had to change the ApiCall.cs because you need to add the content-type to the ByteArrayContent for uploading the image to the Graph Api.

2024-09-01 15:52 UTC, danielpastoor commented
@jansenbe I saw that the "Build and Test" failed but I can't find why this is related to the code that I changed. Do you maybe know if this is related?

2026-05-08 21:43 UTC, Adam-it requested changes
@danielpastoor solid work 👏 and sorry for the huge delay on our side.
May I kindly ask you to go over the few review comments I added before we merge

2026-05-08 21:43 UTC, Adam-it commented on src/sdk/PnP.Core/Model/SharePoint/Branding/Internal/HeaderOptions.cs
> +                    Interactive = true, Content = byteContent
```suggestion
                    Interactive = true, 
                    Content = byteContent
```

2026-05-08 21:43 UTC, Adam-it commented on src/sdk/PnP.Core/Services/Core/BatchClient.cs
I suppose this is not needed now

2026-05-08 21:43 UTC, Adam-it commented on src/sdk/PnP.Core/Services/Core/BatchClient.cs
I guess we do not use this variable now so we could remove it

2026-05-08 21:43 UTC, Adam-it commented on src/sdk/PnP.Core/Model/SharePoint/Branding/Internal/HeaderOptions.cs
> +                    const string cachedSiteIcon = "__siteIcon__.png";
Seems a bit strange in `Reset` method we use `__siteIcon__.jpg`. Maybe we should align

2026-05-08 21:43 UTC, Adam-it commented on src/sdk/PnP.Core/Model/SharePoint/Branding/Internal/HeaderOptions.cs
> +                    !PnPContext.Web.SiteLogoUrl.StartsWith(correctSiteLogoUrl))
won't this always resolve to false as the `SiteLogoUrl` is a full absolute URL, so something like 
```
https://contoso.sharepoint.com/sites/mysite/_api/GroupService/GetGroupImage?id='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'&hash=12345
```
But the `correctSiteLogoUrl`, since it uses `PathAndQuery` will end up as something like:
```
/sites/mysite/_api/GroupService/GetGroupImage?id='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
```
Right?

2026-06-03 19:40 UTC, Adam-it commented
@danielpastoor is there any chance you are still interested in refreshing this PR and resolving the comments I gave? 
Totally understandable if not since your PR was opened very long time ago and we did not have any chance to commit to it so it's 100% on us, but if you are ready for another round I'm here to help and process the PR 🙂

2026-06-22 22:24 UTC, Adam-it commented
@danielpastoor kind reminder 🙏

2026-08-03 20:47 UTC, Adam-it commented
@danielpastoor I will be closing this PR due to lack of activity. 
I am aware that, mainly, that is on us, as this PR was opened a long time ago and you had a long wait before we did any good review of your change, so I do applogize for that. Please be aware that this was not done on purpose.
If anything changes and you would like to get back to this topic in the future please do not hesitate to just reopen the PR and we will be glad to give it another try.
Thank you for all your efforts towards the Microsoft 365 and Power Platform community. You Rock 🤩

2026-08-03 20:47 UTC, closed without merging